version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: market_map
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/market_map
      NEXTAUTH_SECRET: your-secret-key-change-in-production
      NEXTAUTH_URL: http://localhost:3000
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma
    command: >
      sh -c "
        npx prisma db push &&
        npx prisma db seed &&
        npm start
      "

  api:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/market_map
      NODE_ENV: production
    ports:
      - '3001:3001'
    depends_on:
      db:
        condition: service_healthy
    command: npm run server:build

volumes:
  postgres_data: